name: Angular CI

on:
  push:
    branches: [main, develop]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.19.0   # ✅ FIXED

      - name: Install Dependencies
        working-directory: frontend/smartnotes-frontend
        run: npm install